services:
  eureka-server:
    build:
      context: .
      dockerfile: eureka-server/Dockerfile
    image: jack2718/e-commerce-eureka-server:latest
    ports:
      - "8761:8761"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - ENVIRONMENT=${ENVIRONMENT:-local}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-local}
    networks:
      - commerce-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/eureka/apps"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    image: jack2718/e-commerce-api-gateway:latest
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - ENVIRONMENT=${ENVIRONMENT:-local}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-local}
    networks:
      - commerce-net
    command: >
      sh -c "/wait-for-it.sh eureka-server:8761 --timeout=30 --strict &&
             java -Dspring.profiles.active=${SPRING_PROFILES_ACTIVE:-local} -jar app.jar"
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh

  order-service:
    build:
      context: .
      dockerfile: order-service/Dockerfile
    image: jack2718/e-commerce-order-service:latest
    ports:
      - "8081:8081"
    depends_on:
      - eureka-server
      - api-gateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - ENVIRONMENT=${ENVIRONMENT:-local}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-local}
    networks:
      - commerce-net
    command: >
      sh -c "/wait-for-it.sh eureka-server:8761 --timeout=30 --strict &&
             /wait-for-it.sh api-gateway:8080 --timeout=30 --strict &&
             java -Dspring.profiles.active=${SPRING_PROFILES_ACTIVE:-local} -jar app.jar"
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh

  product-service:
    build:
      context: .
      dockerfile: product-service/Dockerfile
    image: jack2718/e-commerce-product-service:latest
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - api-gateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - ENVIRONMENT=${ENVIRONMENT:-local}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-local}
    networks:
      - commerce-net
    command: >
      sh -c "/wait-for-it.sh eureka-server:8761 --timeout=30 --strict &&
             /wait-for-it.sh api-gateway:8080 --timeout=30 --strict &&
             java -Dspring.profiles.active=${SPRING_PROFILES_ACTIVE:-local} -jar app.jar"
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    image: jack2718/e-commerce-user-service:latest
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - api-gateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - ENVIRONMENT=${ENVIRONMENT:-local}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-local}
    networks:
      - commerce-net
    command: >
      sh -c "/wait-for-it.sh eureka-server:8761 --timeout=30 --strict &&
             /wait-for-it.sh api-gateway:8080 --timeout=30 --strict &&
             java -Dspring.profiles.active=${SPRING_PROFILES_ACTIVE:-local} -jar app.jar"
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh

  event-server:
    build:
      context: .
      dockerfile: event-server/Dockerfile
    image: jack2718/e-commerce-event-server:latest
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - api-gateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - ENVIRONMENT=${ENVIRONMENT:-local}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-local}
    networks:
      - commerce-net
    command: >
      sh -c "/wait-for-it.sh eureka-server:8761 --timeout=30 --strict &&
             /wait-for-it.sh api-gateway:8080 --timeout=30 --strict &&
             java -Dspring.profiles.active=${SPRING_PROFILES_ACTIVE:-local} -jar app.jar"
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh

  payment-service:
    build:
      context: .
      dockerfile: payment-service/Dockerfile
    image: jack2718/e-commerce-payment-service:latest
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
      - api-gateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - ENVIRONMENT=${ENVIRONMENT:-local}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-local}
    networks:
      - commerce-net
    command: >
      sh -c "/wait-for-it.sh eureka-server:8761 --timeout=30 --strict &&
             /wait-for-it.sh api-gateway:8080 --timeout=30 --strict &&
             java -Dspring.profiles.active=${SPRING_PROFILES_ACTIVE:-local} -jar app.jar"
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh

  worker-server:
    build:
      context: .
      dockerfile: worker-server/Dockerfile
    image: jack2718/e-commerce-worker-server:latest
    ports:
      - "8086:8086"
    depends_on:
      - eureka-server
      - api-gateway
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
      - ENVIRONMENT=${ENVIRONMENT:-local}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-local}
    networks:
      - commerce-net
    command: >
      sh -c "/wait-for-it.sh eureka-server:8761 --timeout=30 --strict &&
             /wait-for-it.sh api-gateway:8080 --timeout=30 --strict &&
             java -Dspring.profiles.active=${SPRING_PROFILES_ACTIVE:-local} -jar app.jar"
    volumes:
      - ./wait-for-it.sh:/wait-for-it.sh

networks:
  commerce-net:
    driver: bridge
