server:
  port: 8085

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL  # H2 ??????? PostgreSQL ?? ??? ??
    driver-class-name: org.h2.Driver         # H2 JDBC ????
    username: payment                           # ?? ????
    password: payment                           # ?? ???? (??)
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect  # Hibernate H2 Dialect ??
    hibernate:
      ddl-auto: update                       # ??? ?? ?? (??: none, validate, update, create, create-drop)
  h2:
    console:
      enabled: true                          # H2 ?? ???
      path: /h2-console                      # H2 ?? ??

  sql:
    init:
      mode: never

  rabbitmq:
    host: rabbitmq.commerce.svc.cluster.local # raiibtMQ Host
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Eureka URL
    fetch-registry: true
    register-with-eureka: true

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health, info