apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
  namespace: commerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: jack2718/e-commerce-eureka-server:latest
          ports:
            - containerPort: 8761
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            - name: ENVIRONMENT
              value: "dev"
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
          command: [ "/bin/sh", "-c", "java -Dspring.profiles.active=$SPRING_PROFILES_ACTIVE -jar app.jar" ]
          readinessProbe:
            httpGet:
              path: /eureka/apps
              port: 8761
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-server
  namespace: commerce
spec:
  selector:
    app: eureka-server
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: ClusterIP
