apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: commerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:latest
          env:
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "broker,controller"          # Kafka 노드가 broker와 controller 역할을 수행하도록 설정
            - name: KAFKA_CFG_NODE_ID
              value: "1"                           # KRaft 모드에서 각 노드에 부여할 고유 ID (단일 노드의 경우 "1"로 설정)
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "PLAINTEXT:PLAINTEXT"          # 리스너에 대한 보안 프로토콜 매핑
            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:9092"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://kafka.commerce.svc.cluster.local:9092"
          ports:
            - containerPort: 9092
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: commerce
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
      targetPort: 9092
  type: ClusterIP
