apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: commerce
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      initContainers:
        - name: wait-for-deps
          image: alpine:latest
          command:
            - sh
            - -c
            - "apk add --no-cache bash netcat-openbsd && /bin/bash /wait-for-it.sh eureka-server:8761 30 && /bin/bash /wait-for-it.sh api-gateway:8080 30"
          volumeMounts:
            - name: wait-for-it-volume
              mountPath: /wait-for-it.sh
              subPath: wait-for-it.sh
      containers:
        - name: product-service
          image: jack2718/e-commerce-product-service:latest
          ports:
            - containerPort: 8082
          env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: "http://eureka-server:8761/eureka/"
            - name: ENVIRONMENT
              value: "dev"
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
          command: [ "/bin/sh", "-c", "java -Dspring.profiles.active=$SPRING_PROFILES_ACTIVE -jar app.jar" ]
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8082
            initialDelaySeconds: 15
            periodSeconds: 10
      volumes:
        - name: wait-for-it-volume
          configMap:
            name: wait-for-it-config
            defaultMode: 0755
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: commerce
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
