apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-chart.fullname" . }}-api-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "my-chart.labels" . | nindent 4 }}
spec:
  type: {{ if eq .Values.environment "dev" }}ClusterIP{{ else }}LoadBalancer{{ end }}
  ports:
      - protocol: TCP
        port: 80
        targetPort: {{ .Values.apiGateway.port }}
        name: http
  selector:
    app: {{ include "my-chart.fullname" . }}-api-gateway
